language: node_js
node_js:
- lts/*
notifications:
  slack:
    secure: L/XPJ8osrQ+Znw2nTlONAguBqSF+2kuy+sgUo3I37o+8mGpMxtPxzvcJqsDN2XDO2gAVGzMopKlPFUE89UGFPpaeu0OFZVlPeN80IfGZAQ/4nYc6j4HRZRa6/dPN947HPbU09LIXnRqg2Q2fbdhfL5L2Jwf3ntVmSi5AJvuPKTqNdWKOiiLUtnNob+4TM/bi9drePTgZaaSgNIZZWgO4Xn1XGZ7yfvYwi45FJTqcOBA+oRnZCduOq/3BIiE5m4VkbgZQgLEGyNP8pxTtKSlRXRCR4/bBOIt/Lc2eHUHPyMtwZ5dzrJQTHBX2nvrLRkTfizC3YMvFG0UygSe3qYNq40pXM8mYq3hmv7CpvtGSfif3fwzW+W5lnzXTzpwxewTLxFPQkJSKjMsCf5cLffsjjm0UyjTkAesF0BmZyeTlv3NlDBP7Xv0V7ltGxrZnDrZX1P2Q448umlae7N1Y0Zxfkm9YIHH7MPOEoUd592aZuOdTv/M/fFQkhtLMN+T9gNoD0sZ9OP4ZLwOTrk051+4ZbW1aVTm0CGmlR4kH9a9qcENoBJtMfgOlK85YtFrHxse36HOvMwj8TcJEe35bfWPtfB2RxSc+HM6CjZCpQgIW/DggQMeO8CjNpgQPsekwC0LSQnQIVx8ga+I9rO8jI80nKIERNu7opC6Azn1k65C2Ud4=
